# Generated by Django 5.1.3 on 2025-01-03 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_capacity', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Total capacity')),
                ('provisioned_capacity', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Provisioned capacity')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=14, max_digits=16, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=14, max_digits=16, verbose_name='Longitude')),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Frequency')),
                ('width', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Width')),
                ('channel', models.CharField(max_length=5, verbose_name='Channel name')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='optimal_path.connection')),
            ],
        ),
        migrations.AddField(
            model_name='connection',
            name='ending_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='end_connections', to='optimal_path.node'),
        ),
        migrations.AddField(
            model_name='connection',
            name='starting_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='start_connections', to='optimal_path.node'),
        ),
    ]
