# Generated by Django 5.1.3 on 2025-01-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimal_path', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='request_free_id',
            field=models.IntegerField(default=1000, verbose_name='Request Free Id'),
            preserve_default=False,
        ),
    ]
