# Generated by Django 5.1.3 on 2025-01-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimal_path', '0002_channel_request_free_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel',
            field=models.CharField(max_length=5, null=True, verbose_name='Channel name'),
        ),
    ]
