# Generated by Django 5.1.3 on 2025-01-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimal_path', '0003_alter_channel_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='request_free_id',
            field=models.CharField(max_length=64, verbose_name='Request Free Id'),
        ),
    ]
