# Generated by Django 5.1.3 on 2025-01-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimal_path', '0004_alter_channel_request_free_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='frequency',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='request_free_id',
            field=models.CharField(max_length=64, null=True, verbose_name='Request Free Id'),
        ),
    ]
